import type { Metadata } from "next";
import { Geist, Geist_Mono, Saira, Cormorant_Garamond, Poppins } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/smooth-scroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={` ${saira.variable} ${cormorantGaramond.variable} ${poppins.variable} h-full antialiased`}
    >
      <head>
        <script src="/countdown.js" async></script>
        <script src="/scroll-effect.js" async></script>
      </head>
      <body suppressHydrationWarning className="bg-black font-saira-thin min-h-full flex flex-col">
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
